
include ../Makefile.def

EXT		= so
CFLAGS		+= -I../../libga -DGA_MODULE $(AVCCF) $(L5CF) $(SDLCF)
ifeq ($(strip $(GA_ANDROID)),)
LDFLAGS		= #-L../../libga -lga #$(AVCLD) $(SDLLD)
else
LDFLAGS		= --sysroot=$(SYSROOT)
endif

MAKEMODULE	= $(CXX) -o $(TARGET) -shared $^ $(LDFLAGS)

ifeq ($(OS), Darwin)
EXT		= dylib
MAKEMODULE	= $(CXX) -o $(TARGET) -dynamiclib -Wl,-undefined,dynamic_lookup $^ $(LDFLAGS)
endif

.cpp.o:
	$(CXX) -c -g $(CFLAGS) $<

.m.o:
	$(CXX) -c -g $(CFLAGS) $<


